# run from project root dir
services:

  ft_shellfuncs_ubuntu_bash_interactive:
    build: 
      context: ..
      dockerfile: testenv/shellfuncs/bashenv/ubuntu.dockerfile
    container_name: fasttravelcli_shellfuncs_ubuntu_bash_interactive 
    stdin_open: true
    tty: true

  ft_shellfuncs_ubuntu:
    build: 
      context: ..
      dockerfile: testenv/shellfuncs/ubuntu.dockerfile
    container_name: fasttravelcli_shellfuncs_ubuntu_test
    stdin_open: true
    tty: true
  
  ft_cli_ubuntu_bash_interactive:
    build:
      context: ..
      dockerfile: testenv/cli/bashenv/ubuntu.dockerfile
    container_name: fasttravelcli_cli_ubuntu_bash_interactive 
    stdin_open: true
    tty: true

  ft_cli_ubuntu:
    build:
      context: ..
      dockerfile: testenv/cli/ubuntu.dockerfile
    container_name: fasttravelcli_cli_ubuntu_test 
    stdin_open: true
    tty: true


